"""init migration

Revision ID: 42adf88b1dac
Revises: 
Create Date: 2022-07-02 21:36:12.591063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42adf88b1dac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
