"""delete user.has_sale

Revision ID: 4405926c73f2
Revises: 42adf88b1dac
Create Date: 2022-07-02 23:19:25.974923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4405926c73f2'
down_revision = '42adf88b1dac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
