"""add user.patronymic

Revision ID: 52dc1fa6c27f
Revises: 665ad15a1028
Create Date: 2022-07-02 23:39:50.659744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52dc1fa6c27f'
down_revision = '42adf88b1dac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('patronymic', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'patronymic')
    # ### end Alembic commands ###
