"""add user.surname

Revision ID: 665ad15a1028
Revises: 4405926c73f2
Create Date: 2022-07-02 23:37:51.042345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665ad15a1028'
down_revision = '4405926c73f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
