version: "3"
services:
  app:
    build:
      context: app
    stop_signal: SIGKILL
    ports:
      - "5000:5000"
    volumes:
      - ./app/app.py:/var/server/app.py
    networks:
      - psql_flask_net
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    volumes:
      - ./psql_db/:/var/lib/postgresql/data
    command: [ "postgres", "-c",
               "log_destination=stderr", "-c",
               "logging_collector=on", "-c",
               "log_directory=psql_log", "-c",
               "listen_addresses=localhost" ]
    networks:
      - psql_flask_net
    restart: always
networks:
  psql_flask_net:
    driver: bridge