version: "3"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=skillbox_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    volumes:
      - ./psql_db/:/var/lib/postgresql/data
    command: [ "postgres", "-c",
#               "log_destination=stderr", "-c",
               "logging_collector=on", "-c",
               "log_directory=psql_log" ]
    restart: always
  app:
    build:
      context: app
    depends_on:
      - postgres
    stop_signal: SIGKILL
    ports:
      - "5000:5000"
    volumes:
      - ./app/app.py:/var/server/app.py
    restart: always